<?php
$db['order_reservation']=array(
    'columns' => array(
        'id' => array(
            'type' => 'number',
            'required' => true,
            'pkey' => true,
            'extra' => 'auto_increment',
            'label' => '主键id',
            'editable' => false,
        ),
        'order_id' => array(
            'type' => 'table:orders@ome',
            'required' => true,
            'editable' => false,
            'label' => '订单号',
            'in_list' => false,
            'default_in_list' => false,
            'width' => 260,
            'order' => 10,
        ),
        'order_bn' => array(
            'type' => 'varchar(32)',
            'required' => true,
            'label' => '订单号',
            'is_title' => true,
            'width' => 180,
            'searchtype' => 'nequal',
            'editable' => false,
            'filtertype' => 'textarea',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 10,
        ),
        'custom_reserved_status' => array(
            'type' => array(
                '0' => '待确认',
                '1' => '待发货',
                '2' => '确认中',
                '3' => '预约失败',
                //'4' => '预约取消',
                '5' => '已发货',
                '6' => '部分发货',
            ),
            'label' => '客户预约状态',
            'default' => '0',
            'filtertype' => 'yes',
            'filterdefault' => true,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 20,
        ),
        'erp_order_bn' => array(
            'type' => 'varchar(32)',
            'label' => 'SAP单号',
            'editable' => false,
            'searchtype' => 'nequal',
            'filtertype' => 'textarea',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => false,
            'width' => 180,
            'order' => 23,
        ),
        'order_status' => array(
            'type' => array(
                'active' => '活动订单',
                'dead' => '已作废',
                'finish' => '已完成',
            ),
            'default' => 'active',
            'required' => true,
            'label' => '订单状态',
            'width' => 110,
            'hidden' => true,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 26,
            'comment' => '订单状态,可选值:active(活动订单),dead(已作废),finish(已完成)',
        ),
        'pay_status' => array(
            'type' => array(
                0 => '未支付',
                1 => '已支付',
                2 => '处理中',
                3 => '部分付款',
                4 => '部分退款',
                5 => '全额退款',
                6 => '退款申请中',
                7 => '退款中',
                8 => '支付中',
            ),
            'default' => '1',
            'required' => true,
            'label' => '付款状态',
            'width' => 110,
            'editable' => false,
            'filtertype' => 'yes',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 28,
            'comment' => '付款状态,可选值:0(未支付),1(已支付),2(处理中),3(部分付款),4(部分退款),5(全额退款),6(退款申请中),7(退款中),8(支付中)',
        ),
        'process_status' => array(
            'type' => array(
                'unconfirmed' => '未确认',
                'confirmed' => '已确认',
                'splitting' => '部分拆分',
                'splited' => '已拆分完',
                'cancel' => '取消',
                'remain_cancel' => '余单撤销',
                'is_retrial' => '复审订单',
                'is_declare' => '跨境申报订单',
            ),
            'default' => 'unconfirmed',
            'required' => true,
            'label' => '确认状态',
            'width' => 120,
            'editable' => false,
            'filtertype' => 'yes',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'comment' => '订单确认状态',
        ),
        'ship_status' => array(
            'type' => array(
                0 => '未发货',
                1 => '已发货',
                2 => '部分发货',
                3 => '部分退货',
                4 => '已退货',
            ),
            'default'         => '0',
            'required'        => true,
            'label'           => '发货状态',
            'width'           => 110,
            'editable'        => false,
            'in_list'         => true,
            'default_in_list' => true,
            'comment' => '发货状态,可选值:0(未发货),1(已发货),2(部分发货),3(部分退货),4(已退货)'
        ),
        'custom_reserved_mobile' => array(
            'type' => 'varchar(200)',
            'label' => '预约手机号',
            'width' => 180,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 30,
        ),
        'custom_reserved_name' => array(
            'type' => 'varchar(255)',
            'label' => '收货人姓名',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'custom_reserved_area' => array(
            'type' => 'varchar(255)',
            'label' => '收货人省、市、区',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
            'width' => 210,
        ),
        'custom_reserved_address' => array(
            'type' => 'varchar(255)',
            'label' => '收货人地址',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'seller_id' => array(
            'type' => 'table:seller@material',
            'editable' => false,
            'label' => '销售人员名称',
            'in_list' => true,
            'default_in_list' => false,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'width' => 160,
            'order' => 40,
        ),
        'custom_reserved_time' => array(
            'type' => 'time',
            'editable' => false,
            'filtertype' => 'time',
            'filterdefault' => true,
            'label' => '客户预约时间',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 50,
        ),
        'is_reserved_same' => array (
            'type' => array(
                'none' => ' ',
                'true' => 'Yes',
                'false' => 'No',
                'no_confirmed' => 'No-confirmed',
                'confirmed' => 'confirmed',
            ),
            'default' => 'none',
            'editable' => false,
            'label' => '预约时间标记',
            'filtertype' => 'yes',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 55,
        ),
        'is_whole' => array (
            'type' => array(
                'true' => '是',
                'false' => '否',
            ),
            'default' => 'false',
            'editable' => false,
            'label' => '整单发货',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 55,
        ),
        'reserved_version' => array(
            'type' => 'varchar(32)',
            'label' => '预约版本号',
            'width' => 120,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 60,
        ),
        'reserved_result' => array(
            'type' => array(
                'none' => ' ',
                'running' => '执行中',
                'succ' => '成功',
                'fail' => '失败',
            ),
            'label' => '同步状态',
            'default' => 'none',
            'filtertype' => 'yes',
            'filterdefault' => true,
            'editable' => false,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 90,
        ),
        'reservation_items' => array(
            'type' => 'text',
            'label' => '预约明细信息',
            'width' => 260,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 30,
        ),
        'reserved_msg' => array(
            'type' => 'text',
            'label' => '预约信息',
            'width' => 260,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 30,
        ),
        'reserved_remarks' => array(
            'type' => 'text',
            'label' => '预约备注',
            'width' => 260,
            'editable' => false,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 31,
            'comment' => '预约备注(序列化数组：op_name/op_time/op_content)',
        ),
        'reserved_failed_time' => array(
            'type' => 'time',
            'editable' => false,
            'label' => '预约失败时间',
            'in_list' => true,
            'default_in_list' => false,
            'order' => 90,
        ),
        'op_id' => array(
            'type' => 'table:account@pam',
            'label' => '操作员',
            'width'      => 110,
            'editable'   => false,
            'filtertype' => 'normal',
            'in_list'    => true,
            'default_in_list' => false,
        ),
        'at_time' => array(
            'type' => 'TIMESTAMP',
            'label' => '创建时间',
            'default' => 'CURRENT_TIMESTAMP',
            'filtertype' => 'time',
            'filterdefault' => true,
            'in_list' =>  true,
            'default_in_list' => true,
            'order' => 98,
        ),
        'up_time' => array(
            'type' => 'TIMESTAMP',
            'label' => '更新时间',
            'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 99,
        ),
    ),
    'index' => array (
        'ind_order_bn' => array(
            'columns' => array(
                'order_bn',
            ),
            'prefix' => 'unique',
        ),
        'ind_erp_order_bn' => array(
            'columns' => array(
                'erp_order_bn',
            ),
        ),
        'ind_order_pay_status' => array(
            'columns' => array(
                0 => 'order_bn',
                1 => 'order_status',
                2 => 'pay_status',
                3 => 'ship_status',
            ),
        ),
        'ind_reserved_ship_status' => array(
            'columns' => array(
                0 => 'custom_reserved_status',
                1 => 'order_status',
                2 => 'pay_status',
                3 => 'ship_status',
            ),
        ),
        'ind_order_status' => array(
            'columns' => array(
                'order_status',
            ),
        ),
        'ind_pay_status' => array(
            'columns' => array(
                'pay_status',
            ),
        ),
        'ind_process_status' => array(
            'columns' => array(
                'process_status',
            ),
        ),
        'ind_ship_status' => array(
            'columns' => array(
                'ship_status',
            ),
        ),
        'ind_reserved_same' => array(
            'columns' => array(
                'is_reserved_same',
            ),
        ),
        'ind_custom_reserved_time' => array(
            'columns' => array(
                0 => 'custom_reserved_time',
            ),
        ),
        'ind_at_time' => array(
            'columns' => array(
                'at_time',
            ),
        ),
    ),
    'comment' => '订单预约信息表',
    'engine' => 'innodb',
    'version' => '$Rev:  $',
);