<?php
$db['return_reshipping'] = array(
    'columns' => array(
        'reshipping_id' => array(
            'type' => 'bigint unsigned',
            'pkey' => true,
            'extra' => 'auto_increment',
            'editable' => false,
            'comment' => '补寄申请单主键ID，自增',
            'order' => 10,
        ),
        'reshipping_bn' => array(
            'type' => 'varchar(50)',
            'editable' => false,
            'comment' => '补寄申请单号（平台单号）',
            'in_list' => true,
            'default_in_list' => true,
            'is_title' => true,
            'label' => '补寄申请单号',
            'order' => 20,
        ),
        'shop_id' => array(
            'type' => 'table:shop@ome',
            'editable' => false,
            'comment' => '店铺ID',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '店铺',
            'order' => 30,
        ),
        'shop_type' => array(
            'type' => 'varchar(50)',
            'editable' => false,
            'comment' => '店铺类型',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '店铺类型',
            'order' => 31,
        ),
        'order_id' => array(
            'type' => 'table:orders@ome',
            'editable' => false,
            'comment' => '关联订单ID',
            'order' => 40,
        ),
        'order_bn' => array(
            'type' => 'varchar(50)',
            'editable' => false,
            'comment' => '关联订单号',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '关联订单号',
            'order' => 50,
        ),
        'platform_order_bn' => array(
            'type' => 'varchar(50)',
            'editable' => false,
            'comment' => '平台订单号',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '平台订单号',
            'order' => 60,
        ),
        'buyer_address' => array(
            'type' => 'text',
            'editable' => false,
            'comment' => '买家补寄地址',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '买家补寄地址',
            'order' => 70,
        ),
        'buyer_province' => array(
            'type' => 'varchar(100)',
            'editable' => false,
            'comment' => '买家补寄地址省',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '买家补寄地址省',
            'order' => 71,
        ),
        'buyer_city' => array(
            'type' => 'varchar(100)',
            'editable' => false,
            'comment' => '买家补寄地址市',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '买家补寄地址市',
            'order' => 72,
        ),
        'buyer_district' => array(
            'type' => 'varchar(100)',
            'editable' => false,
            'comment' => '买家补寄地址区',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '买家补寄地址区',
            'order' => 73,
        ),
        'buyer_town' => array(
            'type' => 'varchar(100)',
            'editable' => false,
            'comment' => '买家补寄地址镇',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '买家补寄地址镇',
            'order' => 74,
        ),
        'buyer_phone' => array(
            'type' => 'varchar(50)',
            'editable' => false,
            'comment' => '买家联系方式',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '买家联系方式',
            'order' => 80,
        ),
        'buyer_name' => array(
            'type' => 'varchar(100)',
            'editable' => false,
            'comment' => '买家姓名',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '买家姓名',
            'order' => 90,
        ),
        'oaid' => array(
            'type' => 'varchar(250)',
            'editable' => false,
            'comment' => '收件人ID（Open Addressee ID）',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '收件人ID',
            'order' => 100,
        ),
        'buyer_open_uid' => array(
            'type' => 'varchar(100)',
            'editable' => false,
            'comment' => '买家openId',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '买家openId',
            'order' => 110,
        ),
        'real_receiver_open_id' => array(
            'type' => 'varchar(100)',
            'editable' => false,
            'comment' => '收件人加密openId',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '收件人加密openId',
            'order' => 120,
        ),
        'real_receiver_display_nick' => array(
            'type' => 'varchar(100)',
            'editable' => false,
            'comment' => '收件人加密昵称',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '收件人加密昵称',
            'order' => 130,
        ),
        'source' => array(
            'type' => 'varchar(50)',
            'default' => 'matrix',
            'editable' => false,
            'comment' => '数据来源（默认：matrix）',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '数据来源',
            'order' => 140,
        ),
        'operation_contraint' => array(
            'type' => 'varchar(45)',
            'editable' => false,
            'comment' => '操作场景',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '操作场景',
            'order' => 150,
        ),
        'status' => array(
            'type' => 'tinyint unsigned',
            'default' => '0',
            'editable' => false,
            'comment' => '补寄状态（0=补寄待处理，1=等待卖家发货，2=等待买家收货，3=补寄成功，4=卖家拒绝补寄，5=补寄关闭，6=转退款）',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '补寄状态',
            'order' => 40,
        ),
        'refund_phase' => array(
            'type' => "varchar(50)",
            'editable' => false,
            'comment' => '退款阶段（onsale=售中，aftersale=售后）',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '退款阶段',
            'order' => 170,
        ),
        'advance_status' => array(
            'type' => 'varchar(50)',
            'editable' => false,
            'comment' => '先行垫付状态',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '先行垫付状态',
            'order' => 180,
        ),
        'cs_status' => array(
            'type' => 'varchar(30)',
            'editable' => false,
            'comment' => '小二托管状态',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '小二托管状态',
            'order' => 190,
        ),
        'time_out' => array(
            'type' => 'time',
            'editable' => false,
            'comment' => '超时时间（时间戳）',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '超时时间',
            'order' => 200,
        ),
        'refuse_reason' => array(
            'type' => 'varchar(255)',
            'editable' => false,
            'comment' => '拒绝原因',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '拒绝原因',
            'order' => 210,
        ),
        'refuse_reason_id' => array(
            'type' => 'varchar(50)',
            'editable' => false,
            'comment' => '拒绝原因ID',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '拒绝原因ID',
            'order' => 220,
        ),
        'reason' => array(
            'type' => 'varchar(255)',
            'editable' => false,
            'comment' => '补寄申请理由',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '补寄申请理由',
            'order' => 230,
        ),
        'desc' => array(
            'type' => 'text',
            'editable' => false,
            'comment' => '补寄理由说明',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '补寄理由说明',
            'order' => 240,
        ),
        'outer_create_time' => array(
            'type' => 'time',
            'editable' => false,
            'comment' => '外部创建时间（时间戳）',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '外部创建时间',
            'order' => 250,
        ),
        'outer_modified_time' => array(
            'type' => 'time',
            'editable' => false,
            'comment' => '外部修改时间（时间戳）',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '外部修改时间',
            'order' => 260,
        ),
        'at_time' => array(
            'type' => 'TIMESTAMP',
            'default' => 'CURRENT_TIMESTAMP',
            'editable' => false,
            'comment' => '创建时间',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '创建时间',
            'order' => 270,
        ),
        'up_time' => array(
            'type' => 'TIMESTAMP',
            'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
            'editable' => false,
            'comment' => '更新时间',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '更新时间',
            'order' => 280,
        ),
        'reissue_order_id' => array(
            'type' => 'table:orders@ome',
            'editable' => false,
            'comment' => '关联补发订单ID',
            'in_list' => false,
            'default_in_list' => false,
            'label' => '关联补发订单ID',
            'order' => 290,
        ),
        'reissue_order_bn' => array(
            'type' => 'varchar(50)',
            'editable' => false,
            'comment' => '关联补发订单号',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '关联补发订单号',
            'order' => 300,
        ),
        'logi_name' => array(
            'type' => 'varchar(100)',
            'editable' => false,
            'comment' => '卖家发货物流公司名称',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '物流公司名称',
            'order' => 310,
        ),
        'logi_no' => array(
            'type' => 'varchar(100)',
            'editable' => false,
            'comment' => '卖家发货快递单号',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '快递单号',
            'order' => 320,
        ),
        'logi_id' => array(
            'type' => 'bigint unsigned',
            'editable' => false,
            'comment' => '物流公司ID',
            'in_list' => false,
            'default_in_list' => false,
            'label' => '物流公司ID',
            'order' => 330,
        ),
        'is_confirm_goods' => array(
            'type' => [
                '0' => '未确认',
                '1' => '已确认',
            ],
            'default' => '0',
            'editable' => false,
            'comment' => '商品是否已确认（0=未确认，1=已确认）。当is_confirm_goods=1时，说明补寄订单已经创建成功且order_type=bufa',
            'in_list' => true,
            'default_in_list' => true,
            'label' => '商品是否已确认',
            'order' => 340,
        ),
        'extend_field' => array(
            'type' => 'text',
            'editable' => false,
            'comment' => '扩展字段',
            'in_list' => false,
            'default_in_list' => false,
            'label' => '扩展字段',
            'order' => 350,
        ),
    ),
    'index' => array(
        'ind_reshipping_bn' => array(
            'columns' => array(
                0 => 'reshipping_bn',
                1 => 'shop_id',
            ),
            'prefix' => 'unique',
        ),
        'ind_status' => array(
            'columns' => array(
                0 => 'status',
            ),
        ),
        'ind_up_time' => array(
            'columns' => array(
                0 => 'up_time',
            ),
        ),
        'ind_at_time' => array(
            'columns' => array(
                0 => 'at_time',
            ),
        ),
        'ind_platform_order_bn' => array(
            'columns' => array(
                0 => 'platform_order_bn',
            ),
        ),
        'ind_order_bn' => array(
            'columns' => array(
                0 => 'order_bn',
            ),
        ),
    ),
    'comment' => '补寄申请单表，存储补寄申请单的基本信息',
    'engine' => 'innodb',
    'version' => '$Rev:  $',
    'charset' => 'utf8mb4',
);

