<?php
$db['account_chart'] = array(
    'columns' => array(
        'id' => array(
            'type' => 'int',
            'required' => true,
            'pkey' => true,
            'extra' => 'auto_increment',
            'label' => 'ID',
            'comment' => 'ID。自增',
            'editable' => false,
        ),
        'account_code' => array(
            'type' => 'varchar(8)',
            'label' => '会计科目编码',
            'in_list' => true,
            'default_in_list' => true,
            'editable' => false,
        ),
        'account' => array(
            'type' => 'varchar(50)',
            'label' => '会计科目',
            'comment' => '会计科目。索引唯一',
            'in_list' => true,
            'default_in_list' => true,
            'searchtype' => 'nequal',
            'is_title' => true,
            'order' => 30,
            'editable' => false,
        ),
        'description' => array(
            'type' => 'varchar(255)',
            'label' => '科目描述',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 35,
            'editable' => false,
        ),
        'postingkey' => array(
            'type' => 'varchar(30)',
            'label' => '记账码',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 40,
            'editable' => false,
        ),
        'customer' => array(
            'type' => 'varchar(30)',
            'label' => '客户',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 50,
            'editable' => false,
        ),
        'costcenter' => array(
            'type' => 'varchar(30)',
            'label' => '成本中心',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 60,
            'editable' => false,
        ),
        'tax_rate' => array(
            'type' => 'decimal(20,3)',
            'label' => '税率',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 70,
            'editable' => false,
        ),
        'tax_account' => array(
            'type' => 'varchar(50)',
            'label' => '税率会计科目',
            'comment' => '税率会计科目。当有税率时此字段为必填',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 75,
            'editable' => false,
        ),
        'account_category' => array(
            'type' => 'varchar(30)',
            'label' => '应用场景',
            'comment' => 'platform_amount、actually_amount、refundplatform_amount、refundactually_amount每种只能有一条，其余不选的为空',
            'default' => '',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 80,
            'editable' => false,
        ),
        'reason_code' => array(
            'type' => 'varchar(64)',
            'label' => '原因代码',
            'default_in_list' => true,
            'in_list' => true,
            'order' => 65,
            'editable' => false,
        ),
        'disabled' => array(
            'type'     => 'bool',
            'required' => true,
            'default'  => 'false',
            'editable' => false,
            'comment'  => '删除状态,可选值:true(是),false(否)'
        ),
        'at_time' => array(
            'type' => 'TIMESTAMP',
            'label' => '创建时间',
            'default' => 'CURRENT_TIMESTAMP',
            'width' => 150,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 90,
            'editable' => false,
        ),
        'up_time' => array(
            'type' => 'TIMESTAMP',
            'label' => '更新时间',
            'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
            'width' => 150,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 100,
            'editable' => false,
        ),
    ),
    'index' => array(
        'ind_postingkey' => array(
            'columns' => array(0 => 'postingkey'),
        ),
        'ind_customer' => array(
            'columns' => array(0 => 'customer'),
        ),
        'ind_costcenter' => array(
            'columns' => array(0 => 'costcenter'),
        ),
        'ind_account_code' => array(
            'columns' => array(0 => 'account_code'),
            'prefix'  => 'unique',
        ),
    ),
    'comment' => '科目表',
    'engine' => 'innodb',
    'version' => '$Rev:  $',
);
