<?php
/**
 * Copyright 2012-2026 ShopeX (https://www.shopex.cn)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$db['expenses_split']=array (
  'columns' => 
  array (
    'id' => 
    array (
      'type' => 'bigint unsigned',
      'required' => true,
      'pkey' => true,
      'extra' => 'auto_increment',
      'editable' => false,
    ),
    'split_bn' => array(
        'type' => 'varchar(50)',
        'label' => '拆分单号',
        'editable' => false,
        'in_list' => true,
        'default_in_list' => true,
        'filtertype' => 'normal',
        'filterdefault' => true,
        'order' => 2,
    ),
    'bm_id' => array(
      'type' => 'table:basic_material@material',
      'label' => '基础物料名称',
      'width' => 120,
      'editable' => false,
      'in_list' => true,
      'default_in_list' => true,
      'order'=>5,
    ),
    'bill_id' => array(
      'type' => 'table:bill@financebase',
      'label' => '业务流水号',
      'width' => 180,
      'in_list' => true,
      'default_in_list' => true,
      'order'=>10,
    ),
    'parent_id' => array(
      'type' => 'bigint unsigned',
      'label' => '来源ID',
      'width' => 130,
      'order'=>15,
    ),
    'parent_type' => array(
      'type' => 'varchar(32)',
      'label' => '来源类型',
      'width' => 130,
      'order'=>20,
    ),
    'trade_time' => array(
        'type' => 'time',
        'label' => '账单时间',
        'width' => 150,
        'filtertype' => 'normal',
        'filterdefault' => true,
        'editable' => false,
        'in_list' => true,
        'default_in_list' => false,
        'order'=>25,
    ),
    'split_time' => array(
        'type' => 'time',
        'label'=>'拆分时间',
        'width' => 150,
        'filtertype' => 'normal',
        'filterdefault' => true,
        'editable' => false,
        'in_list' => true,
        'default_in_list' => false,
        'order'=>25,
    ),
    'money' => array(
          'type' => 'decimal(20,5)',
          'required' => true,
          'label'=>'分摊费用',
          'width' => 100,
          'editable' => false,
          'in_list' => true,
          'default_in_list' => true,
          'order'=>35,
    ),
    'bill_category' => array(
          'type' => 'varchar(50)',
          'label' => '具体类别',
          'width' => 100,
          'editable' => false,
          'in_list' => true,
          'default_in_list' => true,
          'order'=>30,
    ),
    'split_type' => array(
          'type' => 'varchar(32)',
          'label' => '拆分维度',
          'width' => 100,
          'editable' => false,
          'in_list' => true,
          'default_in_list' => false,
          'order'=>40,
    ),
    'split_rule' => array(
          'type' => 'varchar(32)',
          'label' => '拆分规则',
          'width' => 100,
          'editable' => false,
          'in_list' => true,
          'default_in_list' => false,
          'order'=>45,
    ),
    'split_status' => array(
          'type' => array(
            '0'=>'拆分项',
            '1'=>'调整项',
            '2'=>'红冲项',
          ),
          'label' => '拆分状态',
          'width' => 100,
          'default' => '0',
          'editable' => false,
          'in_list' => true,
          'default_in_list' => false,
          'order'=>45,
    ),
    'porth' => array(
          'type' => 'money',
          'label' => '拆分贡献比',
          'default' => 0,
          'editable' => false,
          'in_list' => true,
          'default_in_list' => false,
          'order'=>50,
    ),
    'shop_id' => array(
            'type' => 'varchar(32)',
            'editable' => false,
            'label' => '来源店铺',
            'comment'=>'来源店铺',
            'width' => 100,
            'order'=>55,
    ),
    'is_accounted' => array(
        'type' => array(
            '0' => '未记账',
            '1' => '已记账',
        ),
        'label' => '是否已记账',
        'default' => '0',
        'editable' => false,
        'in_list' => true,
        'default_in_list' => false,
        'order' => 60,
        'comment' => '标记该拆分项是否已记账',
    ),
    'accounted_time' => array(
        'type' => 'time',
        'label' => '记账时间',
        'width' => 150,
        'filtertype' => 'normal',
        'filterdefault' => false,
        'editable' => false,
        'in_list' => true,
        'default_in_list' => false,
        'order' => 61,
        'comment' => '记账完成时间',
    ),
    'account_id_plus' => array(
        'type' => 'table:account_chart@financebase',
        'label' => '贷会计科目ID',
        'editable' => false,
        'in_list' => true,
        'default_in_list' => true,
        'order' => 65,
    ),
    'account_id_minus' => array(
        'type' => 'table:account_chart@financebase',
        'label' => '借会计科目ID',
        'editable' => false,
        'in_list' => true,
        'default_in_list' => true,
        'order' => 70,
    ),
    'tax_rate_plus' => array(
        'type' => 'decimal(20,3)',
        'label' => '贷方税率',
        'editable' => false,
        'in_list' => true,
        'default_in_list' => true,
        'order' => 75,
    ),
    'tax_amount_plus' => array(
        'type' => 'decimal(20,5)',
        'label' => '贷方税金',
        'editable' => false,
        'in_list' => true,
        'default_in_list' => true,
        'order' => 80,
        'comment' => '根据分摊费用和贷方税率计算的税金',
    ),
    'tax_rate_minus' => array(
        'type' => 'decimal(20,3)',
        'label' => '借方税率',
        'editable' => false,
        'in_list' => true,
        'default_in_list' => true,
        'order' => 85,
    ),
    'tax_amount_minus' => array(
        'type' => 'decimal(20,5)',
        'label' => '借方税金',
        'editable' => false,
        'in_list' => true,
        'default_in_list' => true,
        'order' => 90,
        'comment' => '根据分摊费用和借方税率计算的税金',
    ),
    'order_bn' => array(
        'type' => 'varchar(32)',
        'label' => '订单号',
        'comment' => '订单号',
        'editable' => false,
        'in_list' => true,
        'default_in_list' => true,
        'order' => 95,
        'filtertype' => 'normal',
        'filterdefault' => true,
    ),
    'financial_no' => array(
        'type' => 'varchar(32)',
        'label' => '财务流水号',
        'comment' => '财务流水号',
        'editable' => false,
        'in_list' => true,
        'default_in_list' => true,
        'order' => 96,
        'filtertype' => 'normal',
        'filterdefault' => true,
    ),
    'postingkey_plus' => array(
        'type' => 'varchar(30)',
        'label' => '贷方记账码',
        'comment' => '贷方记账码',
        'editable' => false,
        'in_list' => true,
        'default_in_list' => true,
        'order' => 97,
    ),
    'postingkey_minus' => array(
        'type' => 'varchar(30)',
        'label' => '借方记账码',
        'comment' => '借方记账码',
        'editable' => false,
        'in_list' => true,
        'default_in_list' => true,
        'order' => 98,
    ),
    'costcenter_plus' => array(
        'type' => 'varchar(30)',
        'label' => '贷方成本中心',
        'comment' => '贷方成本中心',
        'editable' => false,
        'in_list' => true,
        'default_in_list' => true,
        'order' => 99,
    ),
    'costcenter_minus' => array(
        'type' => 'varchar(30)',
        'label' => '借方成本中心',
        'comment' => '借方成本中心',
        'editable' => false,
        'in_list' => true,
        'default_in_list' => true,
        'order' => 100,
    ),
    'customer_plus' => array(
        'type' => 'varchar(30)',
        'label' => '贷方客户',
        'comment' => '贷方客户',
        'editable' => false,
        'in_list' => true,
        'default_in_list' => true,
        'order' => 101,
    ),
    'customer_minus' => array(
        'type' => 'varchar(30)',
        'label' => '借方客户',
        'comment' => '借方客户',
        'editable' => false,
        'in_list' => true,
        'default_in_list' => true,
        'order' => 102,
    ),
  ),
  'index' => array(
    'ind_split_bn' => array('columns' => array(0 => 'split_bn'),'prefix' => 'UNIQUE'),
    'ind_trade_time' => array('columns' => array(0 => 'trade_time')),
    'ind_split_time' => array('columns' => array(0 => 'split_time')),
    'ind_split_status' => array('columns' => array(0 => 'split_status')),
    'ind_bill_category' => array('columns' => array(0 => 'bill_category')),
    'ind_is_accounted' => array('columns' => array(0 => 'is_accounted')),
    'ind_order_bn' => array('columns' => array(0 => 'order_bn')),
    'ind_financial_no' => array('columns' => array(0 => 'financial_no')),
    'ind_shop_id' => array('columns' => array(0 => 'shop_id')),
    'ind_accounted_time' => array('columns' => array(0 => 'accounted_time')),
   ),
  'comment' => '费用拆分表',
  'engine' => 'innodb',
  'version' => '$Rev:  $',
);
