<?php
$db['gap'] = array(
    'columns' => array(
        'id' => array(
            'type' => 'int',
            'required' => true,
            'pkey' => true,
            'extra' => 'auto_increment',
            'label' => 'ID',
            'comment' => 'ID。自增',
            'editable' => false,
        ),
        'gap_name' => array(
            'type' => 'varchar(50)',
            'label' => '差异类型',
            'comment' => '差异类型',
            'in_list' => true,
            'default_in_list' => true,
            'searchtype' => 'nequal',
            'is_title' => true,
            'order' => 10,
            'editable' => false,
        ),
        'account_id_plus' => array(
            'type' => 'table:account_chart@financebase',
            'label' => '贷会计科目ID',
            'comment' => '贷会计科目ID',
            'in_list' => false,
            'default_in_list' => false,
            'order' => 20,
            'editable' => false,
        ),
        'account_id_minus' => array(
            'type' => 'table:account_chart@financebase',
            'label' => '借会计科目ID',
            'comment' => '借会计科目ID',
            'in_list' => false,
            'default_in_list' => false,
            'order' => 22,
            'editable' => false,
        ),
        'status' => array(
            'type'  => array(
                "0" => '无效',
                "1" => '有效',
            ),
            'label' => '状态',
            'default' => '1',
            'in_list' => false,
            'default_in_list' => false,
            'order' => 25,
            'editable' => true,
        ),
        'at_time' => array(
            'type' => 'TIMESTAMP',
            'label' => '创建时间',
            'default' => 'CURRENT_TIMESTAMP',
            'width' => 150,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 30,
            'editable' => false,
        ),
        'up_time' => array(
            'type' => 'TIMESTAMP',
            'label' => '更新时间',
            'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
            'width' => 150,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 40,
            'editable' => false,
        ),
    ),
    'index' => array(
        'ind_gap_name' => array(
            'columns' => array(0 => 'gap_name'),
        ),
        'ind_account_id_plus' => array(
            'columns' => array(0 => 'account_id_plus'),
        ),
        'ind_account_id_minus' => array(
            'columns' => array(0 => 'account_id_minus'),
        ),
    ),
    'comment' => '差异表',
    'engine' => 'innodb',
    'version' => '$Rev:  $',
);
