<?php
$db['workflow_record'] = array(
    'columns' => array(
        'id' => array(
            'type' => 'number',
            'required' => true,
            'pkey' => true,
            'extra' => 'auto_increment',
            'label' => '自增主键',
            'editable' => false,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 1,
        ),
        'case_id' => array(
            'type' => 'table:workflow_case@ticket',
            'required' => true,
            'label' => '审批号',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 10,
        ),
        'node_id' => array(
            'type' => 'table:workflow_node@ticket',
            'required' => true,
            'label' => '审批流节点',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'order' => 15,
        ),
        'original_bn' => array(
            'type' => 'varchar(32)',
            'required' => false,
            'label' => '来源单号',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'searchtype' => 'nequal',
            'filtertype' => 'normal',
            'filterdefault' => true,
            'order' => 22,
        ),
        'assignee_type' => array(
            'type' => 'varchar(30)',
            'required' => false,
            'label' => '审批人类型',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 20,
        ),
        'assignee_id' => array(
            'type' => 'number',
            'required' => false,
            'label' => '审批人ID',
            'editable' => true,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 30,
        ),
        'assignee_name' => array(
            'type' => 'varchar(30)',
            'required' => false,
            'label' => '审批人姓名',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'searchtype' => 'nequal',
            'filtertype' => 'normal',
            'order' => 32,
        ),
        'action' => array(
            'type' => 'varchar(20)',
            'required' => true,
            'label' => '节点类型',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'order' => 40,
        ),
        'remark' => array(
            'type' => 'longtext',
            'required' => false,
            'label' => '审批意见',
            'editable' => true,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 50,
        ),
        'status' => array(
            'type' => 'varchar(20)',
            'required' => true,
            'default' => 'pending',
            'label' => '审批状态',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'order' => 25,
        ),
        'process_time' => array(
            'type' => 'time',
            'required' => false,
            'label' => '处理时间',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'time',
            'filterdefault' => true,
            'order' => 90,
        ),
        'at_time' => array(
            'type' => 'TIMESTAMP',
            'label' => '创建时间',
            'default' => 'CURRENT_TIMESTAMP',
            'width' => 135,
            'filtertype' => 'time',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 98,
        ),
        'up_time' => array(
            'type' => 'TIMESTAMP',
            'required' => true,
            'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
            'label' => '更新时间',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 99,
        ),
    ),
    'index' => array (
        'ind_case_id' => array(
            'columns' => array(
                'case_id',
            ),
        ),
        'ind_node_id' => array(
            'columns' => array(
                'node_id',
            ),
        ),
        'ind_original_bn' => array(
            'columns' => array(
                'original_bn',
            ),
        ),
        'ind_assignee_id' => array(
            'columns' => array(
                'assignee_id',
            ),
        ),
        'ind_action' => array(
            'columns' => array(
                'action',
            ),
        ),
        'ind_status' => array(
            'columns' => array(
                'status',
            ),
        ),
        'ind_at_time' => array(
            'columns' => array(
                'at_time',
            ),
        ),
    ),
    'comment' => '审批流审批记录表',
    'engine' => 'innodb',
    'version' => '$Rev:  $',
); 