<?php
$db['workflow_template'] = array(
    'columns' => array(
        'id' => array(
            'type' => 'number',
            'required' => true,
            'pkey' => true,
            'extra' => 'auto_increment',
            'label' => '自增主键',
            'editable' => false,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 1,
        ),
        'template_bn' => array(
            'type' => 'varchar(30)',
            'required' => true,
            'label' => '审批模板编号',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'searchtype' => 'has',
            'filtertype' => 'has',
            'order' => 10,
        ),
        'template_name' => array(
            'type' => 'varchar(50)',
            'required' => true,
            'is_title' => true,
            'label' => '审批模板名称',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'searchtype' => 'has',
            'filtertype' => 'has',
            'order' => 12,
        ),
        'scene_type' => array(
            'type' => 'varchar(50)',
            'required' => true,
            'label' => '审批场景类型',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'searchtype' => 'has',
            'filtertype' => 'has',
            'order' => 20,
        ),
        'description' => array(
            'type' => 'text',
            'required' => false,
            'label' => '流程描述',
            'editable' => true,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 50,
        ),
        'is_enabled' => array(
            'type' => 'bool',
            'label' => '是否启用',
            'default' => 'true',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 90,
        ),
        'version' => array(
            'type' => 'int',
            'label' => '流程版本号',
            'default' => 1,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 92,
        ),
        'at_time' => array(
            'type' => 'TIMESTAMP',
            'label' => '创建时间',
            'default' => 'CURRENT_TIMESTAMP',
            'width' => 135,
            'filtertype' => 'time',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 98,
        ),
        'up_time' => array(
            'type' => 'TIMESTAMP',
            'required' => true,
            'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
            'label' => '更新时间',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 99,
        ),
    ),
    'index' => array (
        'ind_template_bn' => array(
            'columns' => array(
                'template_bn',
            ),
        ),
        'ind_at_time' => array(
            'columns' => array(
                'at_time',
            ),
        ),
    ),
    'comment' => '审批流模板表',
    'engine' => 'innodb',
    'version' => '$Rev:  $',
); 