<?php
$db['workflow_node'] = array(
    'columns' => array(
        'id' => array(
            'type' => 'number',
            'required' => true,
            'pkey' => true,
            'extra' => 'auto_increment',
            'label' => '自增主键',
            'editable' => false,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 1,
        ),
        'node_name' => array(
            'type' => 'varchar(100)',
            'required' => true,
            'is_title' => true,
            'label' => '节点名称',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'searchtype' => 'has',
            'filtertype' => 'has',
            'order' => 10,
        ),
        'node_type' => array(
            'type' => 'varchar(30)',
            'required' => true,
            'label' => '节点类型',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'searchtype' => 'has',
            'filtertype' => 'has',
            'order' => 12,
        ),
        'template_id' => array(
            'type' => 'table:workflow_template@ticket',
            'required' => true,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'label' => '所属审批模板',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 15,
        ),
        'step_order' => array(
            'type' => 'number',
            'required' => true,
            'label' => '节点顺序',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 20,
        ),
        'assignee_type' => array(
            'type' => 'varchar(30)',
            'required' => false,
            'label' => '审批人类型',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'searchtype' => 'has',
            'filtertype' => 'has',
            'order' => 30,
        ),
        'assignee_id' => array(
            'type' => 'number',
            'required' => false,
            'label' => '审批人ID',
            'editable' => true,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 32,
        ),
        'assignee_name' => array(
            'type' => 'varchar(30)',
            'required' => false,
            'label' => '审批人姓名',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'searchtype' => 'has',
            'filtertype' => 'has',
            'order' => 34,
        ),
        'at_time' => array(
            'type' => 'TIMESTAMP',
            'label' => '创建时间',
            'default' => 'CURRENT_TIMESTAMP',
            'width' => 135,
            'filtertype' => 'time',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 98,
        ),
        'up_time' => array(
            'type' => 'TIMESTAMP',
            'required' => true,
            'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
            'label' => '更新时间',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 99,
        ),
    ),
    'index' => array (
        'ind_node_name' => array(
            'columns' => array(
                'node_name',
            ),
        ),
        'ind_template_id' => array(
            'columns' => array(
                'template_id',
            ),
        ),
        'ind_assignee_id' => array(
            'columns' => array(
                'assignee_id',
            ),
        ),
        'ind_at_time' => array(
            'columns' => array(
                'at_time',
            ),
        ),
    ),
    'comment' => '审批流节点表',
    'engine' => 'innodb',
    'version' => '$Rev:  $',
); 