<?php
$db['workflow_case'] = array(
    'columns' => array(
        'id' => array(
            'type' => 'number',
            'required' => true,
            'pkey' => true,
            'extra' => 'auto_increment',
            'label' => '自增主键',
            'editable' => false,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 1,
        ),
        'case_bn' => array(
            'type' => 'varchar(32)',
            'required' => true,
            'is_title' => true,
            'label' => '审批号',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'searchtype' => 'has',
            'filtertype' => 'has',
            'order' => 10,
        ),
        'title' => array(
            'type' => 'varchar(255)',
            'required' => false,
            'label' => '审批标题',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 15,
        ),
        'original_id' => array(
            'type' => 'number',
            'required' => false,
            'label' => '来源ID',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 20,
        ),
        'original_bn' => array(
            'type' => 'varchar(32)',
            'required' => false,
            'label' => '来源单号',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'searchtype' => 'nequal',
            'filtertype' => 'normal',
            'filterdefault' => true,
            'order' => 5,
        ),
        'bill_bn' => array(
            'type' => 'varchar(32)',
            'required' => false,
            'label' => '业务单号',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 30,
        ),
        'bill_type' => array(
            'type' => 'varchar(30)',
            'required' => false,
            'label' => '业务类型',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'order' => 32,
        ),
        'scene_type' => array(
            'type' => 'varchar(50)',
            'required' => false,
            'label' => '审批场景类型',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 34,
        ),
        'items_context' => array(
            'type' => 'text',
            'required' => false,
            'label' => '表单内容',
            'editable' => true,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 60,
        ),
        'status' => array(
            'type' => 'varchar(20)',
            'required' => true,
            'default' => 'pending',
            'label' => '审核状态',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 33,
        ),
        'template_id' => array(
            'type' => 'table:workflow_template@ticket',
            'required' => true,
            'label' => '所属审批模板',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 52,
        ),
        'submitter_id' => array(
            'type' => 'number',
            'required' => false,
            'label' => '提交人ID',
            'editable' => true,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 70,
        ),
        'submitter_name' => array(
            'type' => 'varchar(20)',
            'required' => false,
            'label' => '提交人姓名',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'order' => 72,
        ),
        'current_node_id' => array(
            'type' => 'table:workflow_node@ticket',
            'required' => false,
            'label' => '当前节点',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 40,
        ),
        'current_node_type' => array(
            'type' => 'varchar(30)',
            'required' => true,
            'label' => '当前节点类型',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 42,
        ),
        'start_time' => array(
            'type' => 'time',
            'required' => false,
            'label' => '开始时间',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'time',
            'filterdefault' => true,
            'order' => 42,
        ),
        'end_time' => array(
            'type' => 'time',
            'required' => false,
            'label' => '结束时间',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'time',
            'filterdefault' => true,
            'order' => 44,
        ),
        'assignee_type' => array(
            'type' => 'varchar(30)',
            'required' => false,
            'label' => '审批人类型',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 80,
        ),
        'assignee_id' => array(
            'type' => 'number',
            'required' => false,
            'label' => '审批人ID',
            'editable' => true,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 82,
        ),
        'assignee_name' => array(
            'type' => 'varchar(30)',
            'required' => false,
            'label' => '审批人姓名',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'order' => 84,
        ),
        'at_time' => array(
            'type' => 'TIMESTAMP',
            'label' => '创建时间',
            'default' => 'CURRENT_TIMESTAMP',
            'width' => 135,
            'filtertype' => 'time',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 98,
        ),
        'up_time' => array(
            'type' => 'TIMESTAMP',
            'required' => true,
            'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
            'label' => '更新时间',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 99,
        ),
    ),
    'index' => array (
        'ind_case_bn' => array(
            'columns' => array(
                'case_bn',
            ),
        ),
        'ind_original_bn' => array(
            'columns' => array(
                'original_bn',
            ),
        ),
        'ind_template_id' => array(
            'columns' => array(
                'template_id',
            ),
        ),
        'ind_current_status' => array(
            'columns' => array(
                0 => 'status',
                1 => 'current_node_type',
            ),
        ),
        'ind_current_node_type' => array(
            'columns' => array(
                'current_node_type',
            ),
        ),
        
        
        'ind_at_time' => array(
            'columns' => array(
                'at_time',
            ),
        ),
    ),
    'comment' => '审批流实例表',
    'engine' => 'innodb',
    'version' => '$Rev:  $',
); 